// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlcztempfijlxwsqlxtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3p0ZW1wZmlqbHh3c3FseHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTEyNDksImV4cCI6MjA1Nzk4NzI0OX0.cPj-w-YXCPDkvNNlIDvZbH1XGwltgWWMNxXwhidx0Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);